Economizar/Models/Compra.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Economizar.Models
{
    public class Compra
    {
        public int CompraId { get; set; }

        [Display(Name = "Produto")]
        [Required(ErrorMessage = "O campo {0} precisa ser preenchido")]
        public string Produto { get; set; }

        [DisplayFormat(DataFormatString = "{0:N0}")]
        [Required(ErrorMessage = "O campo {0} precisa ser preenchido")]
        public int Quantidade { get; set; }

        [Display(Name = "Preço")]
        [DataType(DataType.Currency)]
        [DisplayFormat(DataFormatString = "{0:C2}")]
        public decimal Preco { get; set; }

        [DataType(DataType.Currency)]
        [DisplayFormat(DataFormatString = "{0:C2}")]
        public decimal SubTotal { get { return Quantidade * Preco; } }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime DataCompra { get; set; }

        public string Usuario { get; set; }

        public int SupermercadoId { get; set; }
        public virtual Supermercado Supermercado { get; set; }
    }
}

Economizar/Controllers/CompraController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Economizar.Models;

namespace Economizar.Controllers
{
    [Authorize]
    public class CompraController : Controller
    {
        private EconomizarContext db = new EconomizarContext();

        // GET: Compra
        public async Task<ActionResult> Index()
        {
            var compras = db.Compras.Include(c => c.Supermercado);
            ViewBag.DatasCompras = new SelectList(compras.OrderByDescending(l => l.DataCompra), "DataCompra", "DataCompra").Distinct();
            return View(await compras.OrderByDescending(x => x.CompraId).ToListAsync());
        }

        // GET: Compra/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Compra compra = await db.Compras.FindAsync(id);
            if (compra == null)
            {
                return HttpNotFound();
            }
            return View(compra);
        }

        // GET: Compra/Create
        public ActionResult Create()
        {
            ViewBag.SupermercadoId = new SelectList(db.Supermercadoes, "SupermercadoId", "Nome");
            return View();
        }

        // POST: Compra/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "CompraId,Produto,Quantidade,Preco,Usuario,SupermercadoId")] Compra compra)
        {
            if (ModelState.IsValid)
            {
                db.Compras.Add(compra);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.SupermercadoId = new SelectList(db.Supermercadoes, "SupermercadoId", "Nome", compra.SupermercadoId);
            return View(compra);
        }

        // GET: Compra/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Compra compra = await db.Compras.FindAsync(id);
            if (compra == null)
            {
                return HttpNotFound();
            }
            ViewBag.SupermercadoId = new SelectList(db.Supermercadoes, "SupermercadoId", "Nome", compra.SupermercadoId);
            return View(compra);
        }

        // POST: Compra/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "CompraId,Produto,Quantidade,Preco,Usuario,SupermercadoId")] Compra compra)
        {
            if (ModelState.IsValid)
            {
                db.Entry(compra).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.SupermercadoId = new SelectList(db.Supermercadoes, "SupermercadoId", "Nome", compra.SupermercadoId);
            return View(compra);
        }

        // GET: Compra/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Compra compra = await db.Compras.FindAsync(id);
            if (compra == null)
            {
                return HttpNotFound();
            }
            return View(compra);
        }

        // POST: Compra/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Compra compra = await db.Compras.FindAsync(id);
            db.Compras.Remove(compra);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Economizar/Views/Compra/Create.cshtml
@model Economizar.Models.Compra

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Compra</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Produto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Produto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Produto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantidade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantidade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantidade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Preco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Usuario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Usuario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Usuario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SupermercadoId, "SupermercadoId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SupermercadoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SupermercadoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

Economizar/Views/Compra/Delete.cshtml
@model Economizar.Models.Compra

@{
    ViewBag.Title = "Deletar";
}

<h2>Deletar</h2>

<h3>Tem certeza que deseja excluir?</h3>
<div>
    <h4>Compra</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Supermercado.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Supermercado.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Produto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Produto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantidade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantidade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Preco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Preco)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Usuario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Usuario)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Deletar" class="btn btn-danger" />
            @Html.ActionLink("Voltar", "Index", "Compra", new { @class = "btn btn-primary" })
        </div>
    }
</div>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

Economizar/Views/Compra/Details.cshtml
@model Economizar.Models.Compra

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Compra</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Supermercado.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Supermercado.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Produto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Produto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantidade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantidade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Preco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Preco)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Usuario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Usuario)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CompraId }) |
    @Html.ActionLink("Back to List", "Index")
</p>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

Economizar/Views/Compra/Edit.cshtml
@model Economizar.Models.Compra

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Compra</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CompraId)

        <div class="form-group">
            @Html.LabelFor(model => model.Produto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Produto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Produto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantidade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantidade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantidade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Preco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Usuario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Usuario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Usuario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SupermercadoId, "SupermercadoId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SupermercadoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SupermercadoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index", "Compra", new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

Economizar/Views/Compra/Index.cshtml
@model IEnumerable<Economizar.Models.Compra>

@{
    /**/

    ViewBag.Title = "Compras";
}

<h2>Minhas Compras</h2>
<div class="table col-xs-4 col-sm-4 col-md-12 col-lg-12" >
    <table class="table table-hover">
        <tr class="bg-success">
            <th>
                @Html.DisplayNameFor(model => model.Produto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantidade)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Preco)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataCompra)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SubTotal)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Produto)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantidade)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Preco)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataCompra)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SubTotal)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.CompraId }, new { @class = "btn btn-warning" })
                    @Html.ActionLink("Delete", "Delete", new { id = item.CompraId }, new { @class = "btn btn-danger" })
                </td>
            </tr>
        }
    </table>
</div>
<div>
    @Html.ActionLink("Voltar", "Index", "Item", "Item", new { @class = "btn btn-primary" })
</div>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}